SC-6036 Update examples to use the new C/C++ GitHub action
sonarsource-cfamily-examples/linux-cmake-gcovr-gh-actions-sc pull request #3
Opened 2022-11-15 15:47 UTC by bogdanakushnir

2022-11-15 16:02 UTC, tomasz-kaminski-sonarsource approved these changes

2022-11-16 08:55 UTC, nawar-hamo-sonarsource requested changes

2022-11-16 08:55 UTC, nawar-hamo-sonarsource commented on .github/workflows/build.yml
>          uses: actions/setup-python@v2
This dependency is still using nodejs 12 which is deprecated.
Maybe try to upgrade it to v4 to use nodejs 16.

2022-11-16 09:10 UTC, bogdanakushnir commented on .github/workflows/build.yml
>          uses: actions/setup-python@v2
done, looks good.

2022-11-16 09:13 UTC, nawar-hamo-sonarsource approved these changes
LGTM!

2022-11-16 14:49 UTC, merged